# Generated by Django 4.2.1 on 2023-08-26 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('edition', models.CharField(default='First', max_length=64)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(choices=[('Thriller', 'Thriller'), ('Drama', 'Drama'), ('Mystery', 'Mystery'), ('Humor', 'Humor'), ('Comedy', 'Comedy'), ('Religious', 'Religious'), ('Computer Science', 'Computer Science'), ('Poetry', 'Poetry'), ('Sci-Fiction', 'Sci-Fiction'), ('Adventure', 'Adventure'), ('Horror', 'Horror'), ('Novel', 'Novel')], default='null', max_length=64)),
                ('isbn', models.CharField(blank=True, default='null', max_length=64, null=True)),
                ('first_pub', models.DateField(auto_now_add=True, null=True)),
                ('last_pub', models.DateField(auto_now_add=True, null=True)),
                ('language', models.CharField(blank=True, default='English', max_length=100, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('no_of_books', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('reservation_notification_sent', models.BooleanField(default=False)),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('fine', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
