# Generated by Django 4.2.1 on 2023-08-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='first_pub',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Novel', 'Novel'), ('Autobiography', 'Autobiography'), ('Poetry', 'Poetry'), ('Drama', 'Drama'), ('Religious', 'Religious'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Computer Science', 'Computer Science'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Sci-Fiction', 'Sci-Fiction'), ('Adventure', 'Adventure'), ('Humor', 'Humor')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_pub',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='no_of_books',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
