# Generated by Django 4.2.1 on 2023-09-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_genre_reserveditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserveditem',
            old_name='is_read',
            new_name='available_notification_sent',
        ),
        migrations.RemoveField(
            model_name='reserveditem',
            name='message',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Humor', 'Humor'), ('Religious', 'Religious'), ('Drama', 'Drama'), ('Novel', 'Novel'), ('Mystery', 'Mystery'), ('Autobiography', 'Autobiography'), ('Sci-Fiction', 'Sci-Fiction'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Computer Science', 'Computer Science'), ('Poetry', 'Poetry'), ('Adventure', 'Adventure')], max_length=64, null=True),
        ),
    ]
