# Generated by Django 4.2.1 on 2023-09-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_is_read_reserveditem_available_notification_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reservation_notification_sent',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reserved_by',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Thriller', 'Thriller'), ('Novel', 'Novel'), ('Humor', 'Humor'), ('Horror', 'Horror'), ('Drama', 'Drama'), ('Autobiography', 'Autobiography'), ('Religious', 'Religious'), ('Mystery', 'Mystery'), ('Poetry', 'Poetry'), ('Adventure', 'Adventure'), ('Computer Science', 'Computer Science'), ('Sci-Fiction', 'Sci-Fiction'), ('Comedy', 'Comedy')], max_length=64, null=True),
        ),
    ]
